/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto.archivos;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author genec
 */
public class Materiales extends javax.swing.JFrame {

    /**
     * Creates new form Materiales
     */
    public Materiales() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Material");

        jLabel2.setText("Tipo");

        jLabel3.setText("Degradacion");

        jTextField1.setText("jTextField1");

        jTextField2.setText("jTextField2");

        jTextField3.setText("jTextField3");

        jButton1.setText("Ingresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jButton1)))
                .addContainerGap(194, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(jButton1)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String Material = jTextField1.getText();
        String Tipo = jTextField2.getText();
        String Degradacion = jTextField3.getText();
        DateTimeFormatter Fecha =DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss"); 
        boolean Guardar=true;
        if(Material == null||Tipo==null|| Degradacion==null||Fecha==null)
        {
            Guardar = false;
        }
        if(Guardar = true)
        {
            try {
                boolean ingresado=IngresoMaterial(Material, Tipo, Degradacion, Fecha);
            } catch (IOException ex) {
                Logger.getLogger(Materiales.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    public boolean IngresoMaterial(String Material, String Tipo, String Degradacion, DateTimeFormatter Fecha) throws IOException
    {
        //BITACORAAA  ->bitacora materiales y descriptor bitacota ?
        
       boolean SiSePudo = true;
        boolean EsAdmin = false; 
        boolean ActualizaUsuario = false;
        String ruta = "C:/MEIA/Bitacora.txt" ;        
        File archivo = new File(ruta);
        BufferedWriter bw;
        BufferedReader AA;
        String Rol = "";
        String[] RegistrosAMover;
        if(archivo.exists()) 
        {
            try
            {
                AA = new BufferedReader (new FileReader(archivo));
                bw = new BufferedWriter(new FileWriter(archivo.getAbsoluteFile(), true));
                String Linea = AA.readLine();
                int ContadorRegistros = 0;
                if (Linea==null) 
                {
                    //escribios en normal
                 // bw.write(Usuario+"|"+Contrasena+"|"+Nombre+"|"+Apellido+"|"+Nacimiento+"|"+Correo+"|"+Telefono+"|"+Foto+"|"+Rol+"|"+"1"+'\n');
                }
                else
                { 
                    
                    String ruta1 = "C:/MEIA/desc_Bitacora.txt" ;        
                    File archivo1 = new File(ruta1);
                    if(archivo.exists()) 
                    {
                        BufferedReader bw1=new BufferedReader (new FileReader(archivo1));
                        try{
                           bw1 = new BufferedReader(new FileReader(archivo));
                           String Linea1 = bw1.readLine();//nombre
                           String Linea2 = bw1.readLine();//creador
                           String Linea3 = bw1.readLine();//fecha
                           String Linea4 = bw1.readLine();//Cantidad max de Registros
                           String Linea5 = bw1.readLine();//Cantidad total de Registros
                           String Linea6 = bw1.readLine();//Cantidad de Registros acivos 
                           String Linea7 = bw1.readLine();//Cantidad de Registros inactivos
                           String[] parts = Linea1.split("=");
                           String[] parts1 = Linea6.split("=");
                            RegistrosAMover = new String[Integer.parseInt(parts[1])];
                            while(Linea!=null)
                            {
                                RegistrosAMover[ContadorRegistros] = Linea;
                                ContadorRegistros++;
                                Linea = AA.readLine();
                            }
                            BufferedWriter bw2 = new BufferedWriter(new FileWriter(archivo1));
                            bw2.write(Linea1+'\n');
                            bw2.write(Linea2+'\n');
                            bw2.write(Linea3+'\n');
                            bw2.write(Linea4+'\n');
                            if(Integer.toString(ContadorRegistros)==parts[1]) 
                            {
                                bw2.write("Total de registros ="+(ContadorRegistros+1)+'\n');
                                int RActivos = Integer.parseInt(parts1[1])+1;
                                bw2.write("Total de registros activos ="+RActivos+'\n');
                                bw2.write(Linea7+'\n');
                               ActualizaUsuario = true;
                            }
                            else //es la bitacora esa queda iuguak
                            {
                                bw2.write("Total de registros =1"+'\n');
                                bw2.write("Total de registros activos =1"+'\n');
                                bw2.write("Total de registros inactivos =0"+'\n');
                            }
                        }
                        catch(IOException ex){
                            SiSePudo = false;
                        }
                    }
                }
            }
            catch(IOException ex){
                JOptionPane.showMessageDialog(null,"No se puede ingresar un nuevo usuario");
                SiSePudo = false;
            }
        }   
        return false;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Materiales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Materiales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Materiales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Materiales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Materiales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
